### ISSUE TITLE
Add metrics for the server

### ISSUE THREAD

**Issue by kamilongus** [aelve/codesearch#206]
Check following stack: piwik, elk, logdna, papertrail and take the most optimal

**Comment by neongreen** [comment]
NB: we need 

* search logs
* user counts

but we don't need anything else for the launch. Papertrail and Logdna are good for _logs_ but not good for recording searches because the retention period is short.

A Matomo (Piwik) instance is already being set up for a sister project (https://github.com/aelve/guide) so we might be able to reuse it.
